"""Names to be used with IEA datasets.

So fra only contains a data class of dimension names to be used consisently
across all IEA data sets.
"""

import typing as tp
from dataclasses import dataclass

@dataclass(frozen=True, kw_only=True)
class DimNames:
    TIME: str = 'time'
    REGION: str = 'region'
    FLOW: str = 'flow'
    PRODUCT: str = 'product'
    UNIT: str = 'unit'
    GAS: str = 'gas'
    ALLOCATION: str = 'allocation'
###END class dataclass DimNames
dim_names: DimNames = DimNames()


@dataclass(frozen=True, kw_only=True)
class Regions:
    WORLD: str = 'WORLD'
    OECDAM: str = 'OECDAM'
    OECDAO: str = 'OECDAO'
    OECDEUR: str = 'OECDEUR'
    AFRICA: str = 'AFRICA'
    LATAMER: str = 'LATAMER'
    MIDEAST: str = 'MIDEAST'
    EURASIA: str = 'EURASIA'
    ASIA: str = 'ASIA'
    CHINAREG: str = 'CHINAREG'
    WORLDMAR: str = 'WORLDMAR'
    WORLDAV: str = 'WORLDAV'
    ALBANIA: str = 'ALBANIA'
    ALGERIA: str = 'ALGERIA'
    ANGOLA: str = 'ANGOLA'
    ARGENTINA: str = 'ARGENTINA'
    ARMENIA: str = 'ARMENIA'
    AUSTRALI: str = 'AUSTRALI'
    AUSTRIA: str = 'AUSTRIA'
    AZERBAIJAN: str = 'AZERBAIJAN'
    BAHRAIN: str = 'BAHRAIN'
    BANGLADESH: str = 'BANGLADESH'
    BELARUS: str = 'BELARUS'
    BELGIUM: str = 'BELGIUM'
    BENIN: str = 'BENIN'
    BOLIVIA: str = 'BOLIVIA'
    BOSNIAHERZ: str = 'BOSNIAHERZ'
    BOTSWANA: str = 'BOTSWANA'
    BRAZIL: str = 'BRAZIL'
    BRUNEI: str = 'BRUNEI'
    BULGARIA: str = 'BULGARIA'
    CAMBODIA: str = 'CAMBODIA'
    CAMEROON: str = 'CAMEROON'
    CANADA: str = 'CANADA'
    CHILE: str = 'CHILE'
    CHINA: str = 'CHINA'
    COLOMBIA: str = 'COLOMBIA'
    CONGO: str = 'CONGO'
    COSTARICA: str = 'COSTARICA'
    COTEIVOIRE: str = 'COTEIVOIRE'
    CROATIA: str = 'CROATIA'
    CUBA: str = 'CUBA'
    CURACAO: str = 'CURACAO'
    CYPRUS: str = 'CYPRUS'
    CZECH: str = 'CZECH'
    KOREADPR: str = 'KOREADPR'
    CONGOREP: str = 'CONGOREP'
    DENMARK: str = 'DENMARK'
    DOMINICANR: str = 'DOMINICANR'
    ECUADOR: str = 'ECUADOR'
    EGYPT: str = 'EGYPT'
    ELSALVADOR: str = 'ELSALVADOR'
    EQGUINEA: str = 'EQGUINEA'
    ERITREA: str = 'ERITREA'
    ESTONIA: str = 'ESTONIA'
    ETHIOPIA: str = 'ETHIOPIA'
    ESWATINI: str = 'ESWATINI'
    FINLAND: str = 'FINLAND'
    FRANCE: str = 'FRANCE'
    GABON: str = 'GABON'
    GEORGIA: str = 'GEORGIA'
    GERMANY: str = 'GERMANY'
    GHANA: str = 'GHANA'
    GIBRALTAR: str = 'GIBRALTAR'
    GREECE: str = 'GREECE'
    GUATEMALA: str = 'GUATEMALA'
    GUYANA: str = 'GUYANA'
    HAITI: str = 'HAITI'
    HONDURAS: str = 'HONDURAS'
    HONGKONG: str = 'HONGKONG'
    HUNGARY: str = 'HUNGARY'
    ICELAND: str = 'ICELAND'
    INDIA: str = 'INDIA'
    INDONESIA: str = 'INDONESIA'
    IRAN: str = 'IRAN'
    IRAQ: str = 'IRAQ'
    IRELAND: str = 'IRELAND'
    ISRAEL: str = 'ISRAEL'
    ITALY: str = 'ITALY'
    JAMAICA: str = 'JAMAICA'
    JAPAN: str = 'JAPAN'
    JORDAN: str = 'JORDAN'
    KAZAKHSTAN: str = 'KAZAKHSTAN'
    KENYA: str = 'KENYA'
    KOREA: str = 'KOREA'
    KOSOVO: str = 'KOSOVO'
    KUWAIT: str = 'KUWAIT'
    KYRGYZSTAN: str = 'KYRGYZSTAN'
    LAO: str = 'LAO'
    LATVIA: str = 'LATVIA'
    LEBANON: str = 'LEBANON'
    LIBYA: str = 'LIBYA'
    LITHUANIA: str = 'LITHUANIA'
    LUXEMBOU: str = 'LUXEMBOU'
    MADAGASCAR: str = 'MADAGASCAR'
    MALAYSIA: str = 'MALAYSIA'
    MALTA: str = 'MALTA'
    MAURITIUS: str = 'MAURITIUS'
    MEXICO: str = 'MEXICO'
    MOLDOVA: str = 'MOLDOVA'
    MONGOLIA: str = 'MONGOLIA'
    MONTENEGRO: str = 'MONTENEGRO'
    MOROCCO: str = 'MOROCCO'
    MOZAMBIQUE: str = 'MOZAMBIQUE'
    MYANMAR: str = 'MYANMAR'
    NAMIBIA: str = 'NAMIBIA'
    NEPAL: str = 'NEPAL'
    NETHLAND: str = 'NETHLAND'
    NZ: str = 'NZ'
    NICARAGUA: str = 'NICARAGUA'
    NIGER: str = 'NIGER'
    NIGERIA: str = 'NIGERIA'
    NORTHMACED: str = 'NORTHMACED'
    NORWAY: str = 'NORWAY'
    OMAN: str = 'OMAN'
    PAKISTAN: str = 'PAKISTAN'
    PANAMA: str = 'PANAMA'
    PARAGUAY: str = 'PARAGUAY'
    PERU: str = 'PERU'
    PHILIPPINE: str = 'PHILIPPINE'
    POLAND: str = 'POLAND'
    PORTUGAL: str = 'PORTUGAL'
    QATAR: str = 'QATAR'
    ROMANIA: str = 'ROMANIA'
    RUSSIA: str = 'RUSSIA'
    RWANDA: str = 'RWANDA'
    SAUDIARABI: str = 'SAUDIARABI'
    SENEGAL: str = 'SENEGAL'
    SERBIA: str = 'SERBIA'
    SINGAPORE: str = 'SINGAPORE'
    SLOVAKIA: str = 'SLOVAKIA'
    SLOVENIA: str = 'SLOVENIA'
    SOUTHAFRIC: str = 'SOUTHAFRIC'
    SSUDAN: str = 'SSUDAN'
    SPAIN: str = 'SPAIN'
    SRILANKA: str = 'SRILANKA'
    SUDAN: str = 'SUDAN'
    SURINAME: str = 'SURINAME'
    SWEDEN: str = 'SWEDEN'
    SWITLAND: str = 'SWITLAND'
    SYRIA: str = 'SYRIA'
    TAIPEI: str = 'TAIPEI'
    TAJIKISTAN: str = 'TAJIKISTAN'
    TANZANIA: str = 'TANZANIA'
    THAILAND: str = 'THAILAND'
    TOGO: str = 'TOGO'
    TRINIDAD: str = 'TRINIDAD'
    TUNISIA: str = 'TUNISIA'
    TURKEY: str = 'TURKEY'
    TURKMENIST: str = 'TURKMENIST'
    UGANDA: str = 'UGANDA'
    UKRAINE: str = 'UKRAINE'
    UAE: str = 'UAE'
    UK: str = 'UK'
    USA: str = 'USA'
    URUGUAY: str = 'URUGUAY'
    UZBEKISTAN: str = 'UZBEKISTAN'
    VENEZUELA: str = 'VENEZUELA'
    VIETNAM: str = 'VIETNAM'
    YEMEN: str = 'YEMEN'
    ZAMBIA: str = 'ZAMBIA'
    ZIMBABWE: str = 'ZIMBABWE'
    FSUND: str = 'FSUND'
    YUGOND: str = 'YUGOND'
    OTHERAFRIC: str = 'OTHERAFRIC'
    OTHERLATIN: str = 'OTHERLATIN'
    OTHERASIA: str = 'OTHERASIA'
    UNAFRICA: str = 'UNAFRICA'
    UNAMERICAS: str = 'UNAMERICAS'
    UNASIATOT: str = 'UNASIATOT'
    UNEUROPE: str = 'UNEUROPE'
    UNOCEANIA: str = 'UNOCEANIA'
    OECDTOT: str = 'OECDTOT'
    NOECDTOT: str = 'NOECDTOT'
    IEATOT: str = 'IEATOT'
    IEAFAMILY: str = 'IEAFAMILY'
    EU28: str = 'EU28'
    EU27_2020: str = 'EU27_2020'
    MFSU15: str = 'MFSU15'
    MYUGO: str = 'MYUGO'
    OPEC: str = 'OPEC'
    MASEAN: str = 'MASEAN'
    MG7: str = 'MG7'
    MG8: str = 'MG8'
    MG20: str = 'MG20'
    ANNEX1: str = 'ANNEX1'
    ANNEX2: str = 'ANNEX2'
    ANNEX2NA: str = 'ANNEX2NA'
    ANNEX2EU: str = 'ANNEX2EU'
    ANNEX2AO: str = 'ANNEX2AO'
    ANNEX1EIT: str = 'ANNEX1EIT'
    NONANNEX1: str = 'NONANNEX1'
    ANNEXB: str = 'ANNEXB'

REGION: Regions = Regions()

REGION_LONGNAME: Regions = Regions(
    WORLD="World",
    OECDAM="OECD Americas",
    OECDAO="OECD Asia Oceania",
    OECDEUR="OECD Europe",
    AFRICA="Africa",
    LATAMER="Non-OECD Americas",
    MIDEAST="Middle East",
    EURASIA="Non-OECD Europe and Eurasia",
    ASIA="Non-OECD Asia (excluding China)",
    CHINAREG="China (P.R. of China and Hong Kong, China)",
    WORLDMAR="World marine bunkers",
    WORLDAV="World aviation bunkers",
    ALBANIA="Albania",
    ALGERIA="Algeria",
    ANGOLA="Angola",
    ARGENTINA="Argentina",
    ARMENIA="Armenia",
    AUSTRALI="Australia",
    AUSTRIA="Austria",
    AZERBAIJAN="Azerbaijan",
    BAHRAIN="Bahrain",
    BANGLADESH="Bangladesh",
    BELARUS="Belarus",
    BELGIUM="Belgium",
    BENIN="Benin",
    BOLIVIA="Plurinational State of Bolivia",
    BOSNIAHERZ="Bosnia and Herzegovina",
    BOTSWANA="Botswana",
    BRAZIL="Brazil",
    BRUNEI="Brunei Darussalam",
    BULGARIA="Bulgaria",
    CAMBODIA="Cambodia",
    CAMEROON="Cameroon",
    CANADA="Canada",
    CHILE="Chile",
    CHINA="People's Republic of China",
    COLOMBIA="Colombia",
    CONGO="Republic of the Congo",
    COSTARICA="Costa Rica",
    COTEIVOIRE="Côte d'Ivoire",
    CROATIA="Croatia",
    CUBA="Cuba",
    CURACAO="Curaçao/Netherlands Antilles",
    CYPRUS="Cyprus",
    CZECH="Czech Republic",
    KOREADPR="Democratic People's Republic of Korea",
    CONGOREP="Democratic Republic of the Congo",
    DENMARK="Denmark",
    DOMINICANR="Dominican Republic",
    ECUADOR="Ecuador",
    EGYPT="Egypt",
    ELSALVADOR="El Salvador",
    EQGUINEA="Equatorial Guinea",
    ERITREA="Eritrea",
    ESTONIA="Estonia",
    ETHIOPIA="Ethiopia",
    ESWATINI="Kingdom of Eswatini",
    FINLAND="Finland",
    FRANCE="France",
    GABON="Gabon",
    GEORGIA="Georgia",
    GERMANY="Germany",
    GHANA="Ghana",
    GIBRALTAR="Gibraltar",
    GREECE="Greece",
    GUATEMALA="Guatemala",
     GUYANA="Guyana",
    HAITI="Haiti",
    HONDURAS="Honduras",
    HONGKONG="Hong Kong (China)",
    HUNGARY="Hungary",
    ICELAND="Iceland",
    INDIA="India",
    INDONESIA="Indonesia",
    IRAN="Islamic Republic of Iran",
    IRAQ="Iraq",
    IRELAND="Ireland",
    ISRAEL="Israel",
    ITALY="Italy",
    JAMAICA="Jamaica",
    JAPAN="Japan",
    JORDAN="Jordan",
    KAZAKHSTAN="Kazakhstan",
    KENYA="Kenya",
    KOREA="Korea",
    KOSOVO="Kosovo",
    KUWAIT="Kuwait",
    KYRGYZSTAN="Kyrgyzstan",
    LAO="Lao People's Democratic Republic",
    LATVIA="Latvia",
    LEBANON="Lebanon",
    LIBYA="Libya",
    LITHUANIA="Lithuania",
    LUXEMBOU="Luxembourg",
    MADAGASCAR="Madagascar",
    MALAYSIA="Malaysia",
    MALTA="Malta",
    MAURITIUS="Mauritius",
    MEXICO="Mexico",
    MOLDOVA="Republic of Moldova",
    MONGOLIA="Mongolia",
    MONTENEGRO="Montenegro",
    MOROCCO="Morocco",
    MOZAMBIQUE="Mozambique",
    MYANMAR="Myanmar",
    NAMIBIA="Namibia",
    NEPAL="Nepal",
    NETHLAND="Netherlands",
    NZ="New Zealand",
    NICARAGUA="Nicaragua",
    NIGER="Niger",
    NIGERIA="Nigeria",
    NORTHMACED="Republic of North Macedonia",
    NORWAY="Norway",
    OMAN="Oman",
    PAKISTAN="Pakistan",
    PANAMA="Panama",
    PARAGUAY="Paraguay",
    PERU="Peru",
    PHILIPPINE="Philippines",
    POLAND="Poland",
    PORTUGAL="Portugal",
    QATAR="Qatar",
    ROMANIA="Romania",
    RUSSIA="Russian Federation",
    RWANDA="Rwanda",
    SAUDIARABI="Saudi Arabia",
    SENEGAL="Senegal",
    SERBIA="Serbia",
    SINGAPORE="Singapore",
    SLOVAKIA="Slovak Republic",
    SLOVENIA="Slovenia",
    SOUTHAFRIC="South Africa",
    SSUDAN="South Sudan",
    SPAIN="Spain",
    SRILANKA="Sri Lanka",
    SUDAN="Sudan",
    SURINAME="Suriname",
    SWEDEN="Sweden",
    SWITLAND="Switzerland",
    SYRIA="Syrian Arab Republic",
    TAIPEI="Chinese Taipei",
    TAJIKISTAN="Tajikistan",
    TANZANIA="United Republic of Tanzania",
    THAILAND="Thailand",
    TOGO="Togo",
    TRINIDAD="Trinidad and Tobago",
    TUNISIA="Tunisia",
    TURKEY="Republic of Türkiye",
    TURKMENIST="Turkmenistan",
    UGANDA="Uganda",
    UKRAINE="Ukraine",
    UAE="United Arab Emirates",
    UK="United Kingdom",
    USA="United States",
    URUGUAY="Uruguay",
    UZBEKISTAN="Uzbekistan",
    VENEZUELA="Bolivarian Republic of Venezuela",
    VIETNAM="Viet Nam",
    YEMEN="Yemen",
    ZAMBIA="Zambia",
    ZIMBABWE="Zimbabwe",
    FSUND="Former Soviet Union (if no detail)",
    YUGOND="Former Yugoslavia (if no detail)",
    OTHERAFRIC="Other Africa",
    OTHERLATIN="Other non-OECD Americas",
    OTHERASIA="Other non-OECD Asia",
    UNAFRICA="Memo: Africa (UN)",
    UNAMERICAS="Memo: Americas (UN)",
    UNASIATOT="Memo: Asia (UN)",
    UNEUROPE="Memo: Europe (UN)",
    UNOCEANIA="Memo: Oceania (UN)",
    OECDTOT="Memo: OECD Total",
    NOECDTOT="Memo: Non-OECD Total",
    IEATOT="Memo: IEA Total",
    IEAFAMILY="Memo: IEA and Accession/Association countries",
    EU28="Memo: European Union-28",
    EU27_2020="Memo: European Union-27",
    MFSU15="Memo: FSU 15",
    MYUGO="Memo: Former Yugoslavia",
    OPEC="Memo: OPEC",
    MASEAN="Memo: ASEAN",
    MG7="Memo: G7",
    MG8="Memo: G8",
    MG20="Memo: G20",
    ANNEX1="Memo: Annex I Parties",
    ANNEX2="Memo: Annex II Parties",
    ANNEX2NA="Memo: Annex II North America",
    ANNEX2EU="Memo: Annex II Europe",
    ANNEX2AO="Memo: Annex II Asia Oceania",
    ANNEX1EIT="Memo: Annex I EIT",
    NONANNEX1="Memo: non-Annex I Parties",
    ANNEXB="Memo: Annex B Kyoto Parties"
)
